[package]
name = "ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ex-parser = { path="ex-parser" }
ex-span = { path="ex-span" }
ex-symbol = { path="ex-symbol" }

[workspace]
members = [
  "ex-parser",
  "ex-span",
  "ex-symbol"
]
